### ISSUE TITLE
2020-01-23 tc123 M2SS inconsistent TOLD computation error when TOLD not in TIME data

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#161]
### Error

When running tc123 M2SS with nominal time a computation error occurs due to the TOLD value not being in the nominal TIME data. However, when running the same test case with actual time this error does not occur, despite TOLD not being in the actual TIME data either.

Discussion may be required to determine the desired behaviour.

**Edit:** This issue also currently affects actual time as well.

### Description

The following error is given when `mct$TIME == "NOMINAL"`.

```r
Error in run_computation(data = d, map = mct, flag = flags, parameterset = parameterset) : 
  10 Unable to generate dosing interval for Steady State data! TOLD value not found in the provided TIME data
```

This error is very informative and is correct that the TOLD value of 10 is not in the nominal TIME data as shown below. Whether this error should occur or not is unclear.

```r
> table(d[mct$NOMTIME], useNA = "always")

   0 0.25  0.5    1  1.5    2    3    5    8   12   24   48   72   96  120  168  336  504 <NA> 
  20   20   20   20   20   20   20   20   20   20   20   20   20   20   20   20   20   20    0 
```

However this error does not occur for actual time which also doesn't have a time of 10 in it's TIME data. Note: an different error does occur, but it is unclear if it is related and has been documented in #162. 

```r
> table(round(d[mct$ACTTIME], 3), useNA = "always")

      0    0.25     0.5   0.533       1   1.017   1.033     1.5   1.533       2   2.033       3   3.033       5   5.033       8   8.033 
     20      20      15       5      14       1       5      15       5      15       5      15       5      15       5      14       5 
   8.05      12  12.033      24  24.033  24.083    24.1      48  48.083      72      96     120     168 168.017     336 336.017 336.033 
      1      13       7      17       1       1       1      19       1      20      20      20      19       1      13       1       6 
    504 504.033    <NA> 
     15       5       0 
```

This error still occurs when removing the TOLD1 and TAU1 columns from the `flags` dataset.

**Comment by tensfeldt** [comment]
TOLD and TAU are associated with DOSING not PK SAMPLING/OBSERVATIONS so don't have to mirror nominal or actual sampling times in any way. The computation engine should be able to accommodate TOLD and TOLD+TAU values that do not appear in the nominal or actual observation times of the profile.

**Comment by jhhughes256** [comment]
This issue still occurs as of 4097880.

**Comment by tensfeldt** [comment]
The example that provoked this is a realistic one but unusual. The computation engine specifications document provides the guidance that will be used to address this.
In short
TOLD=10 hours
TAU = 6 hours
so the interval runs from TOLD=10 hours to TOLD+TAU = 16 hours.

Nominal Sampling times are available for  8, 12 and 24 hours.
Note ACTUAL times are similar but the behavior MUST be implemented identically. There's no reason to treat ACTUAL and NOMINAL times differently here.

The crux of the problem appears to be that the dosing intervals are only assigned by inspection and comparison to the sampling data points but that is insufficient in a case such as this. 

Since TOLD doesn't align with a sampling time and TOLD+TAU doesn't align with a sampling time, interpolation must be employed in this particular scenario  for both 10 and 16 hours. Observed concentration data points appear for 8 and 12 so 10 can be estimated through interpolation. Observed concentration data points appear for 12 and 24 hours so 16 hours can be estimated through interpolation.

If the scenario was such that the end of the dosing interval, let's use the same one here: 10 - 16 hours didn't have a observed concentration data point "beyond" it to estimate via interpolation, the IF and only IF a terminal elimination slope was estimated, i.e. -KEL, then extrapolation would be used. Here, IF -KEL was avaiable but one of the profiles had no points beyond 12 hours, the 16 hour concentration point for AUCTAU10-16 would be estimated via extrapolation.

The methods above are consistent with the procedures identified in sections 12.1.3 and 12.3 in the computation engine specifications document.

**Comment by rudraya** [comment]
Just to keep everyone updated, as discussed, this issue can be worked around by adding another dosing interval prior to the original one where "TOLD1" is equal to 10 and "TAU1" is equal to 6. We need to define "TOLD1", "TAU1", "TOLD2", and "TAU2" in the MCT and have "TOLD1" equal to 0, "TAU1" equal to 10, "TOLD2" equal to 10 and "TAU2" equal to 6.

**Comment by jhhughes256** [comment]
This testcase currently computes without error for commit 626e458. When making the changes mentioned by @rudraya above the incremental AUCs are generated without `NA`. This seems to be closed to me.
