### ISSUE TITLE
2020-04-01 tc152 M1SD TLAG values are incorrect

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#199]
- Datasets for testcase are loaded to onedrive
- Definition of TLAG from Computation Engine Specifications Document:
This time is defined as the sample time immediately prior to the first quantifiable concentration (non-zero). If all concentrations have a value greater than 0 then TLAG is 0.

The issue is that TLAG is incorrectly generated in this testcase. The Yellow highlights for the CONCTIME1 and CONCTIME2 columns in the image below indicate the correct values for TLAG. TLAG is incorrect for the 2nd and 3rd entries in the parameter results shown.

![image](https://user-images.githubusercontent.com/2399753/78136982-80e51c80-73f2-11ea-8207-8757c7d45b53.png)

Similar to #221  and #220

**Comment by jhhughes256** [comment]
While I don't have access to tc152, I can confirm that with tc1581 this issue occurred with commit e7df513. As of commit cca452d this issue no longer occurs as shown in the output below, therefore this issue is closed.

```r
knitr::kable(r[c(1:4, 21, 28, 34, 39, 66), c("TLAG", "CONC1", "CONC2", "CONC3", "CONC4", "CONC5", "CONCTIME1", "CONCTIME2", "CONCTIME3", "CONCTIME4")])
```

|   | TLAG| CONC1|  CONC2|  CONC3|   CONC4|  CONC5| CONCTIME1| CONCTIME2| CONCTIME3| CONCTIME4|
|:--|----:|-----:|------:|------:|-------:|------:|---------:|---------:|---------:|---------:|
|1  | 0.00|     0|  0.124|  0.676|   0.853|  1.530|         0|       0.3|      0.75|     1.250|
|2  | 0.00|     0|  0.755|  2.400|  15.400| 37.500|         0|       0.3|      0.75|     1.250|
|3  | 0.00|     0|  0.885|  6.070|  11.100| 14.500|         0|       0.3|      0.75|     1.250|
|4  | 0.00|     0| 16.300| 57.100| 113.000| 79.900|         0|       0.3|      0.75|     1.250|
|21 | 0.30|     0|  0.000|  1.130|   1.760|  5.960|         0|       0.3|      0.75|     1.267|
|28 | 1.25|     0|  0.000|  0.000|   0.000| 26.800|         0|       0.3|      0.75|     1.250|
|34 | 0.30|     0|  0.000|  0.321|   2.940|  0.959|         0|       0.3|      0.75|     1.250|
|39 | 0.75|     0|  0.000|  0.000|   0.832|  1.810|         0|       0.3|      0.75|     1.250|
|66 | 0.30|     0|  0.000|  0.279|   1.760|  8.200|         0|       0.3|      0.75|     1.250|
