### ISSUE TITLE
2020-09-01 tc1580 M3SS inconsistent output for SDEID profiles that contain negative times

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#264]
This issue is in regards to scope item 3.16

### Issue

tc1580 contains a single negative time in each profile, with desired behaviour being NA output for all profiles. This behaviour is inconsistent, with some profiles having non-NA values provided in the output for an unknown reason. One profile shows up with this behaviour when running this locally. The automated report .htmls shows up with 4 SDEID profiles being affected.

These SDEID profiles are not mentioned in the warnings like other profiles with this warning: `No parameters generated due to negative TIME values for SDEID: '3970555705'`

```r
# Check number of negative values per profile (and then see how many unique quantities there are)
d$tmpNEGFLAG <- ifelse(d[mct$ACTTIME] < 0, 1, 0)
d %>%
  dplyr::mutate(tmpNEGFLAG = ifelse(d[mct$ACTTIME] < 0, 1, 0)) %>%
  dplyr::group_by(SDEID) %>% 
  dplyr::count(tmpNEGFLAG) %>% 
  dplyr::filter(tmpNEGFLAG == 1) %>% 
  dplyr::pull(n) %>% unique()
#> [1] 1
# every profile has 1 negative value
# What is the negative value?
d[d[mct$ACTTIME] < 0, c("PKATPDnew")]
#>  [1] -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3
#> [40] -3 -3 -3 -3 -3 -3 -3 -3 -3 -3 -3
# What profiles are generating output despite having a negative time? (table below)
knitr::kable(r[!is.na(r$CMAX), c(grep("SDEID", names(r)), grep("MAX", names(r)), grep("^CON.+\\d+$", names(r)))])
# Was this ID mentioned in warnings?
capture.output(warnings()) %>% stringr::str_detect("2848066001") %>% any()
#>   [1] FALSE
```

|   |      SDEID|UDSDEID |  CMAX| CMAX1| CMAX2| CMAXDN| CMAXDN1| CMAXDN2| TMAX| TMAX1| TMAX2| FLGACCEPTTMAX| CONC1| CONC2| CONC3| CONC4| CONC5| CONC6| CONC7| CONC8| CONC9| CONC10| CONC11| CONC12| CONC13| CONC14| CONC15| CONC16| CONC17| CONCTIME1| CONCTIME2| CONCTIME3| CONCTIME4| CONCTIME5| CONCTIME6| CONCTIME7| CONCTIME8| CONCTIME9| CONCTIME10| CONCTIME11| CONCTIME12| CONCTIME13| CONCTIME14| CONCTIME15| CONCTIME16| CONCTIME17|
|:--|----------:|:-------|-----:|-----:|-----:|------:|-------:|-------:|----:|-----:|-----:|-------------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|------:|------:|------:|------:|------:|------:|------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|
|32 | 2848066001|NA      | 31000| 31000|  6980|    310|     310|    69.8|  1.5|   1.5|    13|             1|     0| 10600| 25500| 31000| 20200| 12600| 13100|  6980|  1560|    133|   14.5|      0|      0|      0|      0|      0|     NA|         0|       0.5|  1.016667|       1.5|       2.5|         6|         9|        13|  24.91667|   48.91667|   72.91667|   96.91667|   120.9167|   168.9167|        337|        505|         NA|

**Comment by tensfeldt** [comment]
testing tc1580_M3SS with commit cca452d does demonstrate that the behavior with regards to negative times post dose for input concentration records is inconsistent. SDEID==4068849933 should have had a warning generated since the profile has a negative time for which the FLGEXSDE didn't exclude the datapoint from inclusion in parameter computations.

```r
> #' Profiles/SDEIDs that should either have had warnings displayed in STDOUT from run_computation
> #' but did not or
> #' Were expected to have parameters computed and no warnings issued appropriately.
> k <- is.element(dn[,mct$SDEID], sdeidswithnowarnings)
> knitr::kable(dn[k, c("SDEID", timevar, mct$CONC, "FLGEXKEL","FLGEXSDE")])
```

|    |      SDEID| PKATPDnew| PKCNCN| FLGEXKEL| FLGEXSDE|
|:---|----------:|---------:|------:|--------:|--------:|
|697 | 4068849933|        -3|   7680|        1|        0|


```r
> vlist <- c("SDEID", "SUBJID", timevar, mct$CONC, "FLGEXKEL", "FLGEXAUC", "FLGEXSDE", "FLGEXST")
> knitr::kable(df[df[,mct$SDEID]==sdeidswithnowarnings,vlist])
```

|    |      SDEID|   SUBJID|  PKATPDnew|  PKCNCN| FLGEXKEL| FLGEXAUC| FLGEXSDE| FLGEXST|
|:---|----------:|--------:|----------:|-------:|--------:|--------:|--------:|-------:|
|694 | 4068849933| 10041031|   1.016667|  8790.0|        1|        0|        0|       0|
|695 | 4068849933| 10041031|   1.500000| 11000.0|        1|        0|        0|       0|
|696 | 4068849933| 10041031|   2.500000|  9310.0|        1|        0|        0|       0|
|697 | 4068849933| 10041031|  -3.000000|  7680.0|        1|        0|        0|       0|
|698 | 4068849933| 10041031|   6.000000|  5830.0|        1|        0|        0|       0|
|699 | 4068849933| 10041031|   9.000000|  4430.0|        1|        0|        0|       0|
|700 | 4068849933| 10041031|  13.000000|  2970.0|        1|        0|        0|       0|
|701 | 4068849933| 10041031|  25.000000|  1060.0|        1|        0|        0|       0|
|702 | 4068849933| 10041031|  49.000000|   160.0|        1|        0|        0|       0|
|703 | 4068849933| 10041031|  73.000000|    19.7|        1|        0|        0|       0|
|704 | 4068849933| 10041031|  97.000000|     0.0|        1|        0|        0|       0|
|705 | 4068849933| 10041031| 121.000000|     0.0|        1|        0|        0|       0|
|706 | 4068849933| 10041031| 169.000000|     0.0|        1|        0|        0|       0|
|707 | 4068849933| 10041031| 337.000000|     0.0|        1|        0|        0|       0|
|708 | 4068849933| 10041031| 505.000000|     0.0|        1|        0|        0|       0|
|709 | 4068849933| 10041031|   0.000000|     0.0|        1|        0|        0|       0|
|710 | 4068849933| 10041031|   0.500000|  3220.0|        1|        0|        0|       0|
> 
```

No parameters were computed which is correct but no warnings were generated for SDEID==4068849933 either that no parameters would be generated

```r
> knitr::kable(r[r[,mct$SDEID]==sdeidswithnowarnings,])
```

|   |      SDEID| DOSE1| DOSE2| DOSEC| DOSEC1| DOSEC2| DOF1| CENDINF1| CENDINFDN1| TENDINF1| CMAX| CMAX1| CMAX2| CMAXDN| CMAXDN1| CMAXDN2| FLGACCEPTPREDOSE| CMIN| CMIN1| CMIN2| CMINDN| CMINDN1| CMINDN2| CLAST| CLAST1| CLAST2| TMAX| TMAX1| TMAX2| FLGACCEPTTMAX| TMIN| TMIN1| TMIN2| TLAST| TLAST1| TLAST2| CTROUGH1| CTROUGH2| CTROUGHEND1| CTROUGHEND2| PTROUGHR2| PTROUGHREND1| PTROUGHREND2| KEL| KELC0| KELTMLO| KELTMHI| KELNOPT| KELR| KELRSQ| KELRSQA| FLGACCEPTKEL| THALF| THALFF| LASTTIME| LASTTIME1| LASTTIME2| FLGACCEPTTAU| AUCALL| AUCALLDN1| AUCALLDN2| AUCLAST| AUCLASTDN| AUCLAST1| AUCLAST2| AUCLASTDN1| AUCLASTDN2| AUMCLAST1| AUMCLAST2| AUC1| AUC2| AUC3| AUC4| AUC5| AUC6| AUC7| AUC8| AUC9| AUC10| AUC11| AUC12| AUC13| AUC14| AUC15| AUC1DN| AUC2DN| AUC3DN| AUC4DN| AUC5DN| AUC6DN| AUC7DN| AUC8DN| AUC9DN| AUC10DN| AUC11DN| AUC12DN| AUC13DN| AUC14DN| AUC15DN|AUCINT1 |AUCINT2 |AUCINT3 |AUCINT4 |AUCINT5 |AUCINT6 |AUCINT7 |AUCINT8 |AUCINT9 |AUCINT10 |AUCINT11 |AUCINT12 |AUCINT13 |AUCINT14 |AUCINT15 | AUC0_24| AUC0_12| AUCINFO| AUCINFO1| AUCINFO2| AUCINFOC1| AUCINFOC2| AUCINFODN| AUCINFODN1| AUCINFODN2| CEST| AUCINFP| AUCINFP1| AUCINFP2| AUCINFPC1| AUCINFPC2| AUCINFPDN| AUCINFPDN1| AUCINFPDN2| AUMCINFO1| AUMCINFO2| AUMCINFP1| AUMCINFP2| AUCTAU1| AUCTAU2| AUCTAUDN1| AUCTAUDN2| AUMCTAU1| AUMCTAU2| MRTLAST| MRTLAST1| MRTLAST2| MRTIVIFO1| MRTIVIFO2| MRTIVIFP1| MRTIVIFP2| AUCXPCTO| AUCXPCTO1| AUCXPCTO2| AUCXPCTP| AUCXPCTP1| AUCXPCTP2| AUMCXPTO1| AUMCXPTO2| AUMCXPTP1| AUMCXPTP2| CAV1| CAV2| CLTAU1| CLTAU2| CLTAUW1| CLTAUW2| PTF2| PTR2| VSSO1| VSSO2| VSSP1| VSSP2| VSSOW1| VSSOW2| VSSPW1| VSSPW2| VZTAU1| VZTAU2| VZTAUW1| VZTAUW2| CONC1| CONC2| CONC3| CONC4| CONC5| CONC6| CONC7| CONC8| CONC9| CONC10| CONC11| CONC12| CONC13| CONC14| CONC15| CONC16| CONCTIME1| CONCTIME2| CONCTIME3| CONCTIME4| CONCTIME5| CONCTIME6| CONCTIME7| CONCTIME8| CONCTIME9| CONCTIME10| CONCTIME11| CONCTIME12| CONCTIME13| CONCTIME14| CONCTIME15| CONCTIME16|DI1 |DI2 | TAU2| TOLD2|TIMEU |VOLUMEU |CONCU |KELU |CLU  |AUCU     |AUMCU       |AUCNORMU    |CONCNORMU |VOLUMEWU |CLWU     |   SUBJID|
|:--|----------:|-----:|-----:|-----:|------:|------:|----:|--------:|----------:|--------:|----:|-----:|-----:|------:|-------:|-------:|----------------:|----:|-----:|-----:|------:|-------:|-------:|-----:|------:|------:|----:|-----:|-----:|-------------:|----:|-----:|-----:|-----:|------:|------:|--------:|--------:|-----------:|-----------:|---------:|------------:|------------:|---:|-----:|-------:|-------:|-------:|----:|------:|-------:|------------:|-----:|------:|--------:|---------:|---------:|------------:|------:|---------:|---------:|-------:|---------:|--------:|--------:|----------:|----------:|---------:|---------:|----:|----:|----:|----:|----:|----:|----:|----:|----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|------:|------:|------:|------:|------:|------:|------:|------:|-------:|-------:|-------:|-------:|-------:|-------:|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:-------|:--------|:--------|:--------|:--------|:--------|:--------|-------:|-------:|-------:|--------:|--------:|---------:|---------:|---------:|----------:|----------:|----:|-------:|--------:|--------:|---------:|---------:|---------:|----------:|----------:|---------:|---------:|---------:|---------:|-------:|-------:|---------:|---------:|--------:|--------:|-------:|--------:|--------:|---------:|---------:|---------:|---------:|--------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|---------:|---------:|----:|----:|------:|------:|-------:|-------:|----:|----:|-----:|-----:|-----:|-----:|------:|------:|------:|------:|------:|------:|-------:|-------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|------:|------:|------:|------:|------:|------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|:---|:---|----:|-----:|:-----|:-------|:-----|:----|:----|:--------|:-----------|:-----------|:---------|:--------|:--------|--------:|
|50 | 4068849933|    NA|    NA|    NA|     NA|     NA|   NA|       NA|         NA|       NA|   NA|    NA|    NA|     NA|      NA|      NA|               NA|   NA|    NA|    NA|     NA|      NA|      NA|    NA|     NA|     NA|   NA|    NA|    NA|            NA|   NA|    NA|    NA|    NA|     NA|     NA|       NA|       NA|          NA|          NA|        NA|           NA|           NA|  NA|    NA|      NA|      NA|      NA|   NA|     NA|      NA|           NA|    NA|     NA|       NA|        NA|        NA|           NA|     NA|        NA|        NA|      NA|        NA|       NA|       NA|         NA|         NA|        NA|        NA|   NA|   NA|   NA|   NA|   NA|   NA|   NA|   NA|   NA|    NA|    NA|    NA|    NA|    NA|    NA|     NA|     NA|     NA|     NA|     NA|     NA|     NA|     NA|     NA|      NA|      NA|      NA|      NA|      NA|      NA|NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA      |NA       |NA       |NA       |NA       |NA       |NA       |      NA|      NA|      NA|       NA|       NA|        NA|        NA|        NA|         NA|         NA|   NA|      NA|       NA|       NA|        NA|        NA|        NA|         NA|         NA|        NA|        NA|        NA|        NA|      NA|      NA|        NA|        NA|       NA|       NA|      NA|       NA|       NA|        NA|        NA|        NA|        NA|       NA|        NA|        NA|       NA|        NA|        NA|        NA|        NA|        NA|        NA|   NA|   NA|     NA|     NA|      NA|      NA|   NA|   NA|    NA|    NA|    NA|    NA|     NA|     NA|     NA|     NA|     NA|     NA|      NA|      NA|    NA|    NA|    NA|    NA|    NA|    NA|    NA|    NA|    NA|     NA|     NA|     NA|     NA|     NA|     NA|     NA|        NA|        NA|        NA|        NA|        NA|        NA|        NA|        NA|        NA|         NA|         NA|         NA|         NA|         NA|         NA|         NA|NA  |NA  |   NA|    NA|HR    |L       |NG/ML |1/HR |L/HR |NG.HR/ML |NG.HR.HR/ML |NG.HR/ML/MG |NG/ML/MG  |L/KG     |ML/HR/KG | 10041031|


Warnings from execution with run_computation:

```r
> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
openNCA computation engine version 3.0.0
Computation Run Date/Time: 2020-09-19 19:35:31
unit_conversion : Unit Class 1 (Time) time_col:  DOF1 DOF2 TENDINF1 TENDINF2 TMAX TMAX1 TMAX2 TMIN TMIN1 TMIN2 TLAST TLAST1 TLAST2 KELTMLO KELTMHI THALF LASTTIME LASTTIME1 LASTTIME2 MRTLAST MRTLAST1 MRTLAST2 MRTIVIFO1 MRTIVIFO2 MRTIVIFP1 MRTIVIFP2 TAU1 TAU2 TOLD1 TOLD2  parameters are scaled from  HR  to  HR  via scaling factor:  1 
unit_conversion : Unit Class 3 (Dose) dose_col:  DOSE1 DOSE2  parameters are scaled from  UG  to  MG  via scaling factor:  0.001 
unit_conversion : Unit Class 4 (Volume) volume_col:  VSSO1 VSSO2 VSSP1 VSSP2 VZTAU1 VZTAU2  parameters are scaled from  ML  to  L  via scaling factor:  0.001 
unit_conversion : Unit Class 5 (Amount/Volume) conc_col:  CENDINF1 CENDINF2 CMAX CMAX1 CMAX2 CMIN CMIN1 CMIN2 CLAST CLAST1 CLAST2 CTROUGH1 CTROUGH2 CTROUGHEND1 CTROUGHEND2 KELC0 CEST CAV1 CAV2 CTOLDest1 CTOLDest2  parameters are scaled from  NG/ML  to  NG/ML  via scaling factor:  1 
unit_conversion : Unit Class 6 (1/Time) kel_col:  KEL  parameters are scaled from  1/HR  to  1/HR  via scaling factor:  1 
unit_conversion : Unit Class 7 (Volume/Time) cl_col:  CLTAU1 CLTAU2  parameters are scaled from  ML/HR  to  L/HR  via scaling factor:  0.001 
unit_conversion : Unit Class 8: (Amount.Time/Volume) auc_col:  AUCALL AUCLAST AUCLAST1 AUCLAST2 AUC1 AUC2 AUC3 AUC4 AUC5 AUC6 AUC7 AUC8 AUC9 AUC10 AUC11 AUC12 AUC13 AUC14 AUC15 AUC16 AUC0_24 AUC0_12 AUCINFO AUCINFO1 AUCINFO2 AUCINFOC1 AUCINFOC2 AUCINFP AUCINFP1 AUCINFP2 AUCINFPC1 AUCINFPC2 AUCTAU1 AUCTAU2  parameters are scaled from  NG.HR/ML  to  NG.HR/ML  via scaling factor:  1 
unit_conversion : Unit Class 9: (Amount.Time.Time/Volume) aumc_col:  AUMCLAST1 AUMCLAST2 AUMCINFO1 AUMCINFO2 AUMCINFP1 AUMCINFP2 AUMCTAU1 AUMCTAU2  parameters are scaled from  NG.HR.HR/ML  to  NG.HR.HR/ML  via scaling factor:  1 
unit_conversion : Unit Class 10: ([Amount.Time/Volume]/Amount) aucdn_col:  AUCALLDN1 AUCALLDN2 AUCLASTDN AUCLASTDN1 AUCLASTDN2 AUC1DN AUC2DN AUC3DN AUC4DN AUC5DN AUC6DN AUC7DN AUC8DN AUC9DN AUC10DN AUC11DN AUC12DN AUC13DN AUC14DN AUC15DN AUC16DN AUCINFODN AUCINFODN1 AUCINFODN2 AUCINFPDN AUCINFPDN1 AUCINFPDN2 AUCTAUDN1 AUCTAUDN2  parameters are scaled from  NG.HR/ML/UG  to  NG.HR/ML/MG  via scaling factor:  1000 
unit_conversion : Unit Class 12: ([Amount/Volume]/Amount) concdn_col:  CENDINFDN1 CENDINFDN2 CMAXDN CMAXDN1 CMAXDN2 CMINDN CMINDN1 CMINDN2  parameters are scaled from  NG/ML/UG  to  NG/ML/MG  via scaling factor:  1000 
unit_conversion : Unit Class 14: (Volume/Body Weight) volumew_col:  VSSOW1 VSSOW2 VSSPW1 VSSPW2 VZTAUW1 VZTAUW2  parameters are scaled from  ML/LB  to  L/KG  via scaling factor:  0.002204624 
unit_conversion : Unit Class 15: (Volume/Time/Body Weight) clw_col:  CLTAUW1 CLTAUW2  parameters are scaled from  ML/HR/LB  to  ML/HR/KG  via scaling factor:  2.204624 
There were 50 or more warnings (use warnings() to see the first 50)
> w <- warnings()
> print(w)
Warning messages:
1: In run_computation(data = d, map = mct, flag = flags,  ... :
  Map 'OPTMIZEKEL' does not have a valid value! Not using KEL optmization for this computation
2: In run_M3_SS_computation(data = merged_data, map = map_data,  ... :
  Map 'OPTIMIZEKEL' does not have a valid value! Not using KEL optimization for this computation
3: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '49420991'
4: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '157748714'
5: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '216997173'
6: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '281691464'
7: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '293032605'
8: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '300251841'
9: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '449252031'
10: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '549830008'
11: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '577505261'
12: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '808659093'
13: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '912939988'
14: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '988060330'
15: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1076632905'
16: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1084410289'
17: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1450303224'
18: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1454313505'
19: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1638311658'
20: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1654812592'
21: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1761744862'
22: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1817693860'
23: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '1888352642'
24: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2073132021'
25: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2164211876'
26: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2178496474'
27: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2191860125'
28: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2298543203'
29: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2352705371'
30: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2435740258'
31: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2595576954'
32: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2688143614'
33: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '2831377562'
34: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3021987242'
35: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3022815163'
36: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3260975297'
37: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3485467325'
38: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3497262342'
39: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3504659731'
40: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3557995871'
41: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3687022657'
42: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3781205115'
43: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3884284318'
44: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3889329640'
45: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '3970555705'
46: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '4009722412'
47: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '4011811426'
48: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '4016148147'
49: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '4017028850'
50: In doTryCatch(return(expr), name, parentenv, handler) :
  No parameters generated due to negative TIME values for SDEID: '4037380648'
```

**Comment by jhhughes256** [comment]
This issue has been resolved (or may not have existed in the first place). 

SDEID == 2848066001 is generated as the negative value is set to be ignored by the CE.

```r
> d[d$PKDATAROWID == 315, c("SDEID", "PKATPDnew")]
         SDEID PKATPDnew
139 2848066001        -3
> d[d$PKDATAROWID == 315, c("PKDATAROWID", "SDEID", "PKATPDnew")]
    PKDATAROWID      SDEID PKATPDnew
139         315 2848066001        -3
```

SDEID == 4068849933 does not produce a warning as it exceeds the maximum warnings (n = 50)
